version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: sklep_app
    working_dir: /var/www
    environment:
      TZ: Europe/Kyiv
    volumes:
      - ./:/var/www
    networks:
      - sklep
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: sklep_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sklep

  mysql:
    image: mysql:8.0
    container_name: sklep_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: UTC
    volumes:
      - mysql_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sklep

networks:
  sklep:

volumes:
  mysql_data:
